add mocks data to components
htmlacademy-ecmascript/897219-cinemaddict-15 pull request #4
Opened 2021-08-06 16:05 UTC by owlsua

2021-08-07 10:03 UTC, polRk requested changes

2021-08-07 10:03 UTC, polRk commented on src/view/site-menu.js
> +    )).join('')}
```suggestion
      ${filters.map(filterItemTemplate).join('')}
```

2021-08-07 10:03 UTC, polRk commented on src/view/site-most-commented.js
> +  const sortArray = cards.sort((a,b)=> a.comments.length - b.comments.length).reverse().slice(1, 3);
Это неплохо, но у тебя большая сложность алгоритма, попробуй переписать через reduce

2021-08-07 10:03 UTC, polRk commented on src/view/site-most-commented.js
> +  const sortArray = cards.sort((a,b)=> a.comments.length - b.comments.length).reverse().slice(1, 3);
Представь, что у тебя 1000 cards, ты их можешь отсортировать  и взять 3 последних [cards.length -1, cards.length -2, ...]

https://habr.com/ru/company/yandex/blog/570914/

2021-08-07 10:03 UTC, polRk commented on src/view/site-top-rated.js
> +  const sortArray = cards.sort((a,b)=> a.rating - b.rating).reverse().slice(1, 3);
Оптимизировать

2021-08-07 13:01 UTC, owlsua commented on src/main.js
> +    renderedCardCount += CARD_COUNT_PER_STEP;
а в чем проблема? счетчик же срабатывает.

2021-08-07 13:03 UTC, owlsua commented on src/mock/film-card.js
> +  return dates[randomIndex];
можно, но они на лекции приказали не заморачиваться с моками, скопировал с демо проекта) переделывать?

2021-08-08 04:23 UTC, polRk commented on src/mock/film-card.js
> +  return dates[randomIndex];
Вырабатываем полезную привычку )

2021-08-08 04:25 UTC, polRk commented on src/main.js
> +    renderedCardCount += CARD_COUNT_PER_STEP;
Да, но допустим ты когда-то будешь писать алгоритм, и вот такие крайние случаи ты можешь пропустить, что уже повлияет на конечный результат. Если оставлять в таком виде, то лучше переименовать переменную в `offset`

2021-08-09 08:41 UTC, polRk approved these changes

2021-08-09 08:42 UTC, merged